# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-27 17:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='name household')),
                ('nbr_members', models.IntegerField(default=1, verbose_name='number of members in household')),
                ('address', models.CharField(blank=True, max_length=256, verbose_name='street and number')),
                ('phone', models.CharField(blank=True, max_length=64, verbose_name='phone number')),
                ('postal_code', models.CharField(max_length=32, verbose_name='postal code')),
                ('city', models.CharField(blank=True, max_length=128, verbose_name='city')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='country')),
                ('info', models.TextField(blank=True, null=True, verbose_name='info')),
                ('active', models.BooleanField(default=True, verbose_name='guided at this moment')),
            ],
            options={
                'verbose_name_plural': 'Households',
            },
        ),
        migrations.CreateModel(
            name='MetertypeHousehold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_id', models.CharField(blank=True, max_length=128, verbose_name='meter id')),
                ('order', models.IntegerField(default=0, verbose_name='order, high=more important')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='household.Household')),
            ],
            options={
                'verbose_name_plural': 'MeterTypesHouseholds',
            },
        ),
        migrations.CreateModel(
            name='UserHousehold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='household.Household')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'UsersHouseholds',
            },
        ),
    ]
