# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-27 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('degreeday', '0001_initial'),
        ('meter', '0001_initial'),
        ('household', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metertypehousehold',
            name='meter_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meter.MeterType'),
        ),
        migrations.AddField(
            model_name='household',
            name='degreeday_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='degreeday.DegreedaySource'),
        ),
        migrations.AlterUniqueTogether(
            name='metertypehousehold',
            unique_together=set([('household', 'meter_type')]),
        ),
    ]
