# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-28 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('household', '0002_auto_20161127_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
