# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-27 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Degreeday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_day', models.DateField()),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DegreedaySource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True, verbose_name='name source degree day')),
                ('api_key', models.CharField(blank=True, max_length=512, verbose_name='api key')),
                ('api_secret', models.CharField(blank=True, max_length=512, verbose_name='api key')),
                ('base_temperature', models.FloatField(default='16.5')),
                ('station_id', models.CharField(blank=True, max_length=512, verbose_name='wether station id')),
                ('fetch_url', models.CharField(blank=True, max_length=1024, verbose_name='nase url for fetching info')),
                ('fetch_method', models.CharField(default='aardgas.be', max_length=512, verbose_name='how to fetch data')),
            ],
        ),
        migrations.AddField(
            model_name='degreeday',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='degreeday.DegreedaySource'),
        ),
        migrations.AlterUniqueTogether(
            name='degreeday',
            unique_together=set([('source', 'date_day', 'value')]),
        ),
    ]
