# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-26 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metertype',
            name='is_device',
            field=models.BooleanField(default=False, verbose_name='is a device'),
        ),
    ]
